apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          volumeMounts:
            - name: rails-storage
              mountPath: /rails/storage
      volumes:
        - name: rails-storage
          persistentVolumeClaim:
            claimName: rails-storage-claim
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/app: rubyapi
              app.kubernetes.io/process: web
