version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://search:9200
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:5601/api/status || exit 1" ]
      interval: 5s
      timeout: 3s
    depends_on:
      search:
        condition: service_healthy
  cache:
    image: redis:6.2-alpine
    ports:
    - "6379:6379"
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:9200/_cluster/health?wait_for_status=green&timeout=1s || exit 1 " ]
      retries: 3
      interval: 5s
      timeout: 3s