version: "3"
services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../..:/workspaces:cached
    environment:
      - ELASTICSEARCH_URL=http://search:9200
      - DATABASE_URL=postgres://postgres@database:5432