# fly.toml app configuration file generated for rubyapi-fly-log-shipper on 2024-01-20T10:13:01+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rubyapi-fly-log-shipper"
primary_region = "iad"

[env]
SUBJECT = "logs.rubyapi.>"
VECTOR_LOG = "debug"

[[services]]
http_checks = []
internal_port = 8686

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
