[api]
enabled = true
address = "[::]:8686"

[sources.fly_log_metrics]
type = "internal_metrics"

[sources.nats]
type = "nats"
url = "nats://[fdaa::3]:4223"
queue = "${QUEUE-}"
subject = "${SUBJECT-logs.>}"
auth.strategy = "user_password"
auth.user_password.user = "${ORG-personal}"
auth.user_password.password = "${ACCESS_TOKEN?}"
connection_name = "Fly logs stream"

[transforms.log_json]
type = "remap"
inputs = ["nats"]
source = '''
    . = parse_json!(.message)
    .ddsource = "flyio"
    .host = .fly.app.instance
  '''

[sinks.datadog]
type = "datadog_logs"
inputs = ["log_json"]
default_api_key = "${DATADOG_API_KEY}"
healthcheck.enabled = true
