apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rails-credentials
spec:
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: rails-credentials
    creationPolicy: Owner
  data:
    - secretKey: rails-credentials-secret
      remoteRef:
        key: rubyapi/credentials
        property: master-key
