apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rubyapi
resources:
  # - database.yml
  - web.yaml
  - credentials-key.yml
  - search-credentials.yml
configMapGenerator:
  - name: rails-configmap
    files:
      - .env
  - name: nginx-configmap
    files:
      - nginx.conf
