apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rails-search-credentials
spec:
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: rails-search-credentials
    creationPolicy: Owner
  data:
    - secretKey: endpoint
      remoteRef:
        key: rubyapi/opensearch/rubyapi-prod-application-user
        property: endpoint
    - secretKey: username
      remoteRef:
        key: rubyapi/opensearch/rubyapi-prod-application-user
        property: username
    - secretKey: password
      remoteRef:
        key: rubyapi/opensearch/rubyapi-prod-application-user
        property: password
