apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app.kubernetes.io/app: rubyapi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: rubyapi
      app.kubernetes.io/process: web
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: rubyapi
        app.kubernetes.io/process: web
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/app: rubyapi
              app.kubernetes.io/process: web
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: web
          image: ghcr.io/rubyapi/rubyapi/rubyapi:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["bundle exec rails server -p 3000 -b 0.0.0.0"]
          envFrom:
            - configMapRef:
                name: rails-configmap
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-credentials
                  key: rails-credentials-secret
            - name: SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: rails-search-credentials
                  key: endpoint
            - name: SEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: rails-search-credentials
                  key: username
            - name: SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rails-search-credentials
                  key: password
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 1250m
              memory: 1280Mi
          livenessProbe:
            exec:
              command:
                - bin/pumactl status
              initialDelaySeconds: 5
              periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
      initContainers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
